apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot-service
  namespace: rag-chatbot
  labels:
    app: rag-chatbot
spec:
  type: NodePort
  selector:
    app: rag-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000    # FastAPI uvicorn port in app.py
      nodePort: 30080     # Access externally: http://54.224.133.12:30080
